ospere:
  allowedHosts: "ospere.example.com"
  csrfTrustedOrigins: "https://ospere.example.com"
  mef:
    environment: "ats"
    clientSystemIDs:
      - "client-system"
      - "client-system-secondary"
    clientSystemID: "client-system"
    efin: "123456"
    etin: "12345"
    softwareID: "11122233"
    endpointURL: "https://example.com/mef"
    cert:
      secretName: "ospere-mef-cert"

aws:
  s3:
    artifactsBucket: "ospere-artifacts"
    schemasBucket: "ospere-schemas"

database:
  host: "postgres.example.com"

secrets:
  create: true
  djangoSecretKey:
    value: "ci-secret-key"
  postgresPassword:
    value: "password"
  celeryBrokerURL:
    value: "redis://redis:6379/0"
  celeryResultBackend:
    value: "django-db"

worker:
  enabled: true

beat:
  enabled: true

ingress:
  enabled: true
  hosts:
    - host: ospere.example.com
      paths:
        - path: /
