{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ospere.fullname" . }}
  labels:
    {{- include "ospere.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.djangoSecretKey.value }}
  {{ .Values.secrets.djangoSecretKey.key }}: {{ .Values.secrets.djangoSecretKey.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.postgresPassword.value }}
  {{ .Values.secrets.postgresPassword.key }}: {{ .Values.secrets.postgresPassword.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.celeryBrokerURL.value }}
  {{ .Values.secrets.celeryBrokerURL.key }}: {{ .Values.secrets.celeryBrokerURL.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.celeryResultBackend.value }}
  {{ .Values.secrets.celeryResultBackend.key }}: {{ .Values.secrets.celeryResultBackend.value | b64enc }}
  {{- end }}
{{- end }}
