{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extractor.fullname" . }}
  labels:
    {{- include "extractor.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.databaseURL.value }}
  {{ .Values.secrets.databaseURL.key }}: {{ .Values.secrets.databaseURL.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.anthropicAPIKey.value }}
  {{ .Values.secrets.anthropicAPIKey.key }}: {{ .Values.secrets.anthropicAPIKey.value | b64enc }}
  {{- end }}
{{- end }}