aws:
  s3Bucket: "kfai-testing-cache"

extractor:
  logLevel: "ERROR"

  models:
    haiku: us-gov.anthropic.claude-3-haiku-20240307-v1:0
    sonnet: us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0
    vlmClassifier: us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0
    vlmDateExtractor: us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0
    parserModel: us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0
    checkModel: us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0

datePipelineArtifacts:
  rfdetrStampDateDetectorCheckpoint: s3://kfai-testing-cache/models/vlm_stamp_date_detector/base/checkpoint_best_total.pth
  vlmStampDateReaderCheckpoint: s3://kfai-testing-cache/models/vlm_stamp_date_reader/v4/mistralai/Ministral-3-3B-Instruct-2512-BF16/checkpoint-2500
  vlmStampDateBaseModel: s3://kfai-testing-cache/models/ministral-3-3b-instruct-2512-bf16/
  gem4encStampDateReaderCheckpoint: s3://kfai-testing-cache/models/gem4enc_stamp_date_reader/stage2-full-280/checkpoint-5000/
